### ISSUE TITLE
Problème lors de l'utilisation du plugin jarvis-calendar

### ISSUE THREAD

**Issue by samwel89** [RobyBioloid/jarvis-calendar#1]
Bonjour,

Je viens d'installer le plugin jarvis-calendar. J'ai bien suivi l'activation API Google calendar et changer le nom du fichier json.
Mais il y a des soucis au niveau des demandes. Il y a les erreurs quand je demande **"Quels sont les événements à venir"** mais aussi quand je fais **"Ajoute-moi un événement"**, çà se passe bien au niveau des questions mais à la fin çà donne les erreurs comme il y a un échec dans l'ajout, bizarrement quand je refaire la demande **"Quels sont les événements à venir"** il va me donner les lignes des erreurs et l’événement que j'ai ajouté. Voici des photos pour bien montrer les logs. J'en ai besoin votre aide ou les idées svp. Merci d'avance.

![image](https://cloud.githubusercontent.com/assets/26720867/24410130/8b1de200-13d2-11e7-974e-336eae1e6ac8.png)

![image](https://cloud.githubusercontent.com/assets/26720867/24410002/2cf944da-13d2-11e7-9d63-f17eb13281e8.png)

**Comment by Amonbofils** [comment]
J'ai le meme probleme ... impossible de le faire fonctionner

**Comment by RobyBioloid** [comment]
Ça fonctionne chez moi. Je me penche sur le problème et vous tiens au courant

**Comment by Amonbofils** [comment]
dans le descriptif je vois : 
### DEPENDANCE
```
Ce plugin à besoin : 
- De la librairie Google client,
```

Y'a-t-il quelque chose de spécifique a faire ? 
Pour info, quand je regarde la ligne suivante : 
```
Cannot access /home/pi/.credentials/calendar-python-quickstart.json
```

Effectivement le fichier n’apparaît pas chez moi. Doit manquer quelque chose

**Comment by RobyBioloid** [comment]
J'ai posté une MAJ qui devrait régler le problème

Lors de la première utilisation, le navigateur internet doit s'ouvrir et il faut aller sur le compte Google en question et autoriser l’accès.

**Comment by samwel89** [comment]
Salut @RobyBioloid 

J'ai fait le MAJ et m'a dirigé au navigateur à la page de mon Google Agenda, j'ai bien autoriser l'accès.
Mais maintenant j'ai cet erreur de "NoneType". voici la photo, merci d'avance.

![image](https://cloud.githubusercontent.com/assets/26720867/24507855/ed2e0f34-1561-11e7-8162-19dcff363512.png)

**Comment by Amonbofils** [comment]
Meme chose pour moi !

**Comment by samwel89** [comment]
Bonjour @RobyBioloid 

As-tu regardé cette erreur? Merci.

**Comment by vinceHH** [comment]
bonjour,

meme probleme pour moi :
![image](https://cloud.githubusercontent.com/assets/26817494/24563638/73f5b344-164f-11e7-8fd3-417da4c13680.png)

l'important est ici : 
If your browser is on a different machine then exit and re-run this application with the command-line parameter  --noauth_local_webserver

n'ayant pas de navigateur sur le raspberry, est il possible de prevoir une option pour rajouter ce parametre --noauth_local_webserver  ?

merci

**Comment by RobyBioloid** [comment]
Bonjour,

Tu as l'adresse d'autorisation ici
Your browser has been opened to visit:
"Lien vers la page d'activation"

Fais un copier coller dans un autre navigateur et ça devait rouler.

**Comment by RobyBioloid** [comment]
@vinceHH , j'ai modifié le fichier 'activationAPI' en précisant à la fin une procédure qui pourrait t'intéresser.
Peux tu tester et me faire un retour

:)

**Comment by vinceHH** [comment]
Bonjour,

Merci pour ton retour et la procédure détaillée.
Etant sous windows, j'ai bien installé python, distribute et pip
La commande pip install --upgrade google-api-python-client s'est bien passée.

par contre, je bloque à l'étape "Lancez le script 'google-calendar-permission.py'"
Je cherche mais je ne trouve pas le script :(

on y est presque :)

**Comment by RobyBioloid** [comment]
lol c'est normal j'ai oublié de le poser. Je m'en occupe de suite

PS : C'est fait

**Comment by vinceHH** [comment]
J'ai pris un peu d'avance, j'ai vu que tu as poussé le script 'jarvis-calendar-permission.py'
Mais quand je le lance, pas de navigateur qui se lance et j'obtiens pas mal d'erreur sur la non presence de fichiers : 
![image](https://cloud.githubusercontent.com/assets/26817494/24705112/b5b61f26-1a0a-11e7-83cb-81035ee892bb.png)

**Comment by RobyBioloid** [comment]
Oui j'ai oublié de préciser qu'il faut le fichier clientsecrets.json.

Je vais le rajouter.

Sinon il faut que télécharge le 'client_secret.json' et que tu le place ou le script est exécuté

**Comment by vinceHH** [comment]
je le trouve où ? j'ai rien dans le .credentials sur le raspberry

il parle également du fichier calendar-pythin-quickstart.json

**Comment by RobyBioloid** [comment]
C'est normal que le fichier 'calendar-pyhon-quickstart.json' soit manquant car il est généré par le script via le fichier 'client_secret.json'

Donc si tu n'a pas déposé le fichier 'client_secret.json' il va forcément manquer deux fichiers

- Va sur le lien ci-dessous
https://console.developers.google.com

- Vérifie être sur le bon compte google en haut à droite

- Clique sur identifiiant à gauche

Tu dois avoir une ligne sous ID clients OAuth 2.0 avec le nom que tu as renseigné lors de l'activation de l'API
-Clique dessus.
En haut tu dois avoir "Telecharger json"

**Comment by vinceHH** [comment]
Hello,

c'est bon, j'ai remis les choses dans l'ordre et ça fonctionne :)

le fichier client_secret.json doit etre placé dans le répertoire courant du lancement de la commande (dans le repertoire de python.exe dans mon cas)

Merci pour ton aide, cela fonctionne maintenant !
