### ISSUE TITLE
problème jarvis calendar

### ISSUE THREAD

**Issue by Clovis-krz** [RobyBioloid/jarvis-calendar#2]
Bonjour,
Je viens d'installer le plugin calendar, suivi l'activation de google-api et installé dans le fichier python du plugin le .json après l'avoir renommé bien sûr !
Après de nombreuses tentatives le programme me retournait toujours une erreur jusqu'à ce que j'installe la librairie google (merci les commentaires sous les plugins ). Je décide de faire un test en keyboard mode et j'ajoute un événement. Puis je le retrouve dans mon téléphone....jusque là tout allait bien !! Mais malheureusement, je recommence en mode normal ajoute un titre, description, lieu, heure de début et heure de fin..puis il me retourne une erreur qui reste la même à chaque fois : 

Traceback (most recent call last):
  File "/home/pi/jarvis/plugins/jarvis-calendar/python/createEvent.py", line 97, in <module>
    createEvent()
  File "/home/pi/jarvis/plugins/jarvis-calendar/python/createEvent.py", line 43, in createEvent
    startDateTime = dateTime[2] + '-' + get_intMonth(dateTime[1]) + '-' + dateTime[0] + 'T' + heure[0] + ':' + heure[2] + ':00+01:00'
IndexError: list index out of range

j'ai recommencé en keyboard mode mais  cette erreur apparaissait également.
Je ne trouve pas de solution pour l'instant ni si ce n'est que je suis content d'avoir réussis au moins une fois et ça me donne bon espoir pour la suite.
Merci d'avance de vos réponses.

**Comment by wikijm** [comment]
Erreur du même type de mon côté :

> Traceback (most recent call last):
>     File "/home/pi/jarvis/plugins/jarvis-calendar/python/nextEvent.py", line 60, in <module>
>         nextEvent()
>     File "/home/pi/jarvis/plugins/jarvis-calendar/python/nextEvent.py", line 48, in nextEvent
>         location = event['location']
> KeyError: 'location'

Voir http://asciinema.org/a/0iv0r04osus9wr0lunw2njcwi

**Comment by RobyBioloid** [comment]
@wikijm  c'est une erreur de fichier manquant.

Les événements doivent avoir les champs "Titre", "Lieu", "Description", "jour", "heure début", "heure fin" sinon ca plante.

Il doit avoir dans un de tes événement le lieu qui n'est pas précisé.

PS : j'ai modifié le code. Tiens moi au courant

**Comment by RobyBioloid** [comment]
@Clovis-krz  je faisais mes test en mode keyboard et il est vrai qu'en mode "normal" les choses sont un peu plus complexe car la retranscription de ce que l'on dit n'est pas toujours faite comme on le souhaite.

Je pense que l'événement que tu as voulu créer datait d'avant le 10 du mois

J'ai remarqué que quand on donné une date, bing speech recognizer écrivait les nombres de 1 à 10 en lettre "un" "deux", "trois', etc .. et les nombres de 11 à ... en chiffres "11", "12", "13", etc ... alors que quand on donne une heure c'est toujours écrit sous la forme numérique. :s

Du coup les événement 9 avril 2017 sont retranscrites "neuf avril 2017" et la : plantage car neuf n'est pas reconnu dans le code.

Je corrige cela aujourd'hui

**Comment by wikijm** [comment]
@RobyBioloid En déplacement actuellement, je te ferais un retour dès que possible.
Merci pour ta rapidité de prise en compte 😉 

N'hésites pas à clôturer le ticket si je mets trop de temps à faire un retour  :sweat_smile:
