### ISSUE TITLE
décalage horaire

### ISSUE THREAD

**Issue by fredissimo06** [RobyBioloid/jarvis-calendar#3]
Salut

lorsque l'on crée un nouvelle événement l'heure est resté a l'heure d'hivers, du coup, si on met par exemple une heure de début a 19h00, ça rajoute l’événement a 20h00. Bien sur idem pour l'heure de fin.

dans le fichier createevent.py, j'ai modifié les deux lignes qui détermine les heures en passant de +1 a +2.
et ca marche.
J'en ai conclus que c’était un problème de conversion d'heure GMT.

Est ce que tu saurais déterminer si on est en heure d'hivers ou en heure d'été automatiquement  ?
via un if ou autre chose, je ne connais pas les langages.

sinon super plugin, il y a encore quelque bugs reportés dans les autres issues, donc je n'en parlerais pas ici :).

Merci

**Comment by RobyBioloid** [comment]
Salut @fredissimo06,

Content que le plugin t’intéresse 

Il est possible de gérer l'heure d'hiver et l'heure d'été automatiquement. je m'en occupe des que possible.

Il y a encore des bugs je sais mais on se rapproche de ce que je voulais :)

**Comment by RobyBioloid** [comment]
J'ai modifié le code pour qu'il prenne en compte l'heure d'hivers ou d'été jusqu'en 2032 pour le moment ;)

**Comment by fredissimo06** [comment]
super, merci.
Je teste tout ça se soir :)

**Comment by fredissimo06** [comment]
parfait, merci
je ne connais pas trop les usages, mais je pense qu'on peut clore :)

**Comment by RobyBioloid** [comment]
N'hésite pas si tu rencontre d'autres problèmes ou si tu vois des améliorations à apporter :)
