### ISSUE TITLE
Ajout d'un evénement : Message : If your browser is on a different machine then exit and re-run this application with the command-line parameter

### ISSUE THREAD

**Issue by pacanou** [RobyBioloid/jarvis-calendar#4]
Bonjour,
A la fin de l'ajout d'un événement, j'ai un message : 
If your browser is on a different machine then exit and re-run this application with the command-line parameter

et l'événement n'est pas crée.

merci.

ajoute un évènement
eva: Oui bien sûr. Quel est le titre de l'événement à ajouter ?
anniversaire de carole
eva: Où doit il se dérouler ?
paris
eva: Donnez moi une petite description de l'événement ?
qui aura du monde
eva: Quel jour aura lieu l'événement ?
cinq avril
eva: A quelle heure ?
à 18h
eva: Quel jour prendra fin l'événement ?
cinq avril
eva: A quelle heure ?
à 18h
eva: Confirmez vous l'ajout de l'événement. Titre : anniversaire de carole
eva: , lieu : paris
eva: , description : qui aura du monde
eva: , avec comme date de début : cinq avril
eva: , à à 18h
eva: , avec comme date de fin : cinq avril
eva: , à à 18h
 *OUI*                   *NON*
oui

Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&response_type=code&client_id=336220126830-q1ec60a2l93549qpbm2ffr1844serqra.apps.googleusercontent.com&access_type=offline

If your browser is on a different machine then exit and re-run this
application with the command-line parameter

  --noauth_local_webserver

**Comment by RobyBioloid** [comment]
Le message "if your browser is on a different machine then exit and re-run this application ..." apparait quand Jarvis n'arrive pas à lancer le navigateur pour l'autorisation.

Cela arrive pour les personnes qui n'ont pas de navigateur internet installé sur leur Raspberry. (Est-ce ton cas?)

Sinon pour les réponses aux questions, il faut répondre que l’essentiel.
Quel titre ?
-> Donner uniquement le titre tel que tu le souhaite dans ton événement
Ou doit se dérouler l'événement ?
-> si tu dit : "Paris" ou "à Paris" ou "euh, ça sera à Paris", le lieu sera textos ce que tu as dit
Quel jour aura lieu l'événement ?
-> Tu as trois possiblité : aujourd'hui, demain ou une autre date sous la forme jour mois année (24 avril 2017) si tu dit "le 24 avril 2017" ça plantera!
A quelle heure ?
-> il faut juste donner l'heure sans rien avant ni apres : ex : "18h" ("à 18h" plantera")
etc ...

**Comment by RobyBioloid** [comment]
Pour ceux qui ont un soucis d'activation de l'API via le navigateur internet, un solution à été ajouté à la fin du fichier 'activationAPI'

**Comment by RobyBioloid** [comment]
@pacanou .

Je me suis permis d'alléger ton post pour y voir plus clair.

J'ai relevé deux problème te concernant.

Premier problème:
Il faut bien penser à répondre correctement aux questions posé par 'eva'. Surtout pour les questions de date et d'heure
Quel jour aura lieu l'événement?
Tu dois répondre : aujourd'hui, demain ou une autre date sous la forme 'jour mois année' ex : 'cinq avril 2017'. ('cinq avril' ne fonctionnera pas)
A quelle heure?
Tu dois juste dire une heure : 18h, 18 heure, 18 heure trente.
'à 18h' ne fonctionnera pas

Deuxième problème:
Ton navigateur n'arrive pas à ouvrir le lien d'activation de l'API

Si tu n'as pas de navigateur internet d'installé sur la machine où 'Jarvis' est installé. Tu peux suivre les indications se trouvant à la fin du fichier 'activation_API' .

Tiens moi informé :)

**Comment by pacanou** [comment]
Merci de  de votre retour. J'ai un raspberry 3 avec jessie d'installé et le navigateur par défaut. Faut il installer un autre navigateur chrome ou firefox ?

Sinon quand j'execute le script, j'ai ce message  (je suis novice) : 
pi@raspberrypi:~/jarvis/plugins/jarvis-calendar/python $ python google-calendar-permission.py
**python: can't open file 'google-calendar-permission.py': [Errno 2] No such file or directory**

le fichier client_secret.json et jarvis-calendar-permission.py se trouve dans le même dossier : 
/jarvis/plugins/jarvis-calendar/python/

**Comment by RobyBioloid** [comment]
Normalement, tu n'as pas besoin de lancer le script 'google-calendar-permission.py'

Il est la juste pour les personnes qui n'ont pas de navigateur sur leur Raspberry

Si tu as une Raspberry avec Jessie dessus tu devrais avoir le navigateur Chromium d'installé par défaut donc ça devrait fonctionner normalement

As-tu bien pensé à suivre les étapes indiqué dans le fichier 'activationAPI' ?
- création du projet avec activation de l'API et téléchargement du clientsecret.json?

**Comment by pacanou** [comment]
oui, j'ai suivi à la lettre de ce qu'il y'avait indiqué dans activationAPI, j'ai obtenu l'APi et téléchargé le fichier json puis renommer en client_secret.json puis copié dans le dossier python. 
Est ce que ca peut venir d'n problème de droit ?

**Comment by pacanou** [comment]
Ayé trouvé, en faite je me connecté en ssh avec putty depuis mon PC pour me connecter sur mon raspb. J'ai installé vnc viewer sur mon rasp en ligne de commande voir tuto : 

http://www.framboise314.fr/prenez-la-main-a-distance-sur-votre-raspberry-pi-avec-vnc/

me suis connecté via VNC et à partir du terminal de mon raspb, j'ai lancé jarvis puis votre plugin et cette fois ci le navigateur s'est bien ouvert et puis j'ai pu autoriser la connexion. Ajout d'un événement OK.
Merci pour le plugin. Je test les autres fonctions .
