### ISSUE TITLE
Consulter les prochains événements : TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by pacanou** [RobyBioloid/jarvis-calendar#5]
Bonsoir,

Quand je demande à consulter les prochains événement à venir, j'ai une erreur : 

quels sont les prochains événements à venir
$> echo "" > ~/jarvis/plugins/jarvis-calendar/python/event.txt && jv_calendar_ne                                            xtEvent
Traceback (most recent call last):
  File "/home/pi/jarvis/plugins/jarvis-calendar/python/nextEvent.py", line 71, i                                            n <module>
    nextEvent()
  File "/home/pi/jarvis/plugins/jarvis-calendar/python/nextEvent.py", line 33, i                                            n nextEvent
    if debut[8:10] == now[8:10] :
TypeError: 'NoneType' object has no attribute '__getitem__'

Dans le fichier nextEvent.py à la ligne 33, j'ai : 
        if debut[8:10] == now[8:10] :

puis à la ligne 71 : nextEvent()

Si vous avez une idée ?

**Comment by RobyBioloid** [comment]
Je pense savoir pourquoi tu as cette erreur.

Tu dois avoir dans l'un de tes 10 prochains événements un événement qui est prévu pour la journée entière.

Du coup il n'y a pas d'heure de début et de fin!

Je m'occupe de corriger ça

**Comment by RobyBioloid** [comment]
J'ai fait une mise à jour

Peux tu la tester et me faire un retour

**Comment by pacanou** [comment]
Bonjour,

Oui, çà fonctionne mieux, il me cite mes 5 prochains événements mais la journée de demain, il informe que j'ai toujours qq chose alors que je n'ai rien dans mon calendrier de prévu. Soit ici anniversaire de MOMO demain alors que c'est en décembre. Merci

quels sont mes prochains événements
$> echo "" > ~/jarvis/plugins/jarvis-calendar/python/event.txt && jv_calendar_nextEvent
eva: Vos 5 prochains événements sont :
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
eva: Le 14 mai 2017 , FETE PAPA.
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
eva: Le 08 novembre 2017 , ANNIVERSAIRE DE NOEL.
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
eva: Le 07 decembre 2017 à 13 heure 47, Anniversaire Mam.
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
eva: Demain , ANNIVERSAIRE MOMO.
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
eva: Le 17 decembre 2017 à 13 heure 47, ANNIVERSSAIRE DE NALANY.
DEBUG: start_speaking hook
DEBUG: stop_speaking hook

**Comment by RobyBioloid** [comment]
Je viens de corriger le problème
