### ISSUE TITLE
Créer un évènement erreur

### ISSUE THREAD

**Issue by SwithFr** [RobyBioloid/jarvis-calendar#6]
Bonjour lorsqu'il me demande le titre de mon évènement : 

`./jarvis.sh: line 628: /Users/Joha/jarvis/plugins/jarvis-calendar/python/event.txt: No such file or directory`

Le fichier existe bien la clé API est activé et le client_secret.json est bien dans le dossier python...

Merci

**Comment by RobyBioloid** [comment]
Est ce que tu arrives à consutler les événements?

L'erreur viendrait non pas du plugin mais du fichier jarvis.sh 'core de Jarvis'

Fait un copier coller de l'erreur en mode troubleshooting

**Comment by RobyBioloid** [comment]
As tu toujours le problême ?

**Comment by SwithFr** [comment]
Je n'ai pas encore eu l'occasion de tester. Je reviens vers toi dès que ça sera fait.

**Comment by RobyBioloid** [comment]
Ok.

Je ferme le ticket pour le moment ;)
