### ISSUE TITLE
Problème "prochain evenement"

### ISSUE THREAD

**Issue by AlainGr** [RobyBioloid/jarvis-calendar#8]
Bonjou,
Déjà bravo à tous pour le travail réalisé.
J'ai un petit soucis avec ce plugin, il fonctionne correctement sauf la consultation du prochain événement qui me renvoie systématiquement  ce message 
prochain evenement
Traceback (most recent call last):
  File "/home/pi/jarvis/plugins_installed/jarvis-calendar/python/nextEvent.py", line 86, in <module>
    nextEvent()
  File "/home/pi/jarvis/plugins_installed/jarvis-calendar/python/nextEvent.py", line 77, in nextEvent
    reply += date + heure + ", " + summary + ".\n"
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 15: ordinal not in range(128)
et ce quelque soit l'événement entré (avec titre, date de début et de fin, lieu et description le tout sans accent). Je ne pense pas avoir vu de réponse à cette erreur dans les tickets fermés.
Une idée de ce que j'ai pu louper ?? Merci

**Comment by RobyBioloid** [comment]
Salut @AlainGr .

Désolé de ne répondre que maintenant mais je ne suis pas toujours sur le projet

Le bug à été corrigé

Cordialement

**Comment by AlainGr** [comment]
Magnifique, tout fonctionne.
Merci
